deliver:
    messages: 'hello, this properties from local'

spring:
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


management:
    shutdown:
      enabled: true # 更流畅的关闭应用
    endpoints:
      web:
        exposure:
          include: "*"