spring:
  application:
    name: shopping-product-description

server:
  port: 8762


eureka:
  instance:
    prefer-ip-address: true
    hostname: shopping-product-description
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


feign:
  hystrix:
    enabled: true # 开启feign hystrix 服务
  client:
    config:
      shopping-product-server:
        connectTimeout: 5000 # 设置feign客户端连接请求超时时间
        readTimeout: 5000 # 设置feign客户端连接的访问时间,如果连接时间过小，那么会触发熔断以及降级服务。
        loggerLevel: basic

client:
  username: admin
  password: 123456

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #设置hystrixcommand的熔断以及降级服务

management:
    shutdown:
      enabled: true # 更流畅的关闭应用
    endpoints:
      web:
        exposure:
          include: "*"




#spring:
#  security:
#    user:
#      name: admin
#      password: 123456
#      roles: TEST_ROLES



